name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - xarray
  - pandas<1.3 # remove this once https://github.com/pydata/xarray/issues/5581 is released
  - netcdf4
  - scipy
  - xgcm
  - cftime
  - regionmask
  - xarrayutils
  - pytest-cov
  - pytest-xdist
  - codecov
