name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - numpy
  - pandas
  - intake-esm
  - xgcm
  - pyproj
  - matplotlib
  - regionmask # this will fail until the current version is released on conda
  - pip:
    - codecov
    - pytest-cov
    - black